# The dot product

### Definition of the dot product

The *dot product* of two vectors $\mathbf{x}$ and $\mathbf{y}$ from $\mathbb{R}^n,$ written as $\mathbf{x}\cdot\mathbf{y},$ is defined as the sum of the entry-wise scalar products 

$$ \mathbf{x}\cdot\mathbf{y} = \sum_{k=1}^n x_k y_k $$

where $\mathbf{x} = (x_1,\ldots, x_n)$ and $\mathbf{y} = (y_1,\ldots, y_n).$ 

(The dot product is an inner product.)

Consequences of the definition of the dot product:
1. Vectors $\mathbf{x}$ and $\mathbf{y}$ must have the same number of entries in order to take their dot product.
2. $\mathbf{x} \cdot \mathbf{y}$ is real number, i.e. $\mathbf{x} \cdot \mathbf{y} \in \mathbb{R}.$
3. $\mathbf{x} \cdot \mathbf{y} = \mathbf{y} \cdot \mathbf{x}.$

In [1]:
import numpy as np

In [3]:
# code example with vectors x and y.
# Notice these vectors have single [] in this representation.

x = np.array([0,1,2])
print(x)
print(type(x))
print("")

y = np.array([3,4,5])
print(y)
print(type(y))
print("")

# the np.inner() command just takes these 'vectors.' No need to worry about col or row representation.
# This is the dot product of x and y.  Check the calculation by hand.
np.inner(x,y)

[0 1 2]
<class 'numpy.ndarray'>

[3 4 5]
<class 'numpy.ndarray'>



14

In [5]:
# check that np.inner(y,x) is the same as above.
np.inner(y,x)

14

### Dot product as matrix product

The dot product can also be represented by a row vector multiplied on the right by a column vector.

Let $\mathbf{x}, \mathbf{y} \in \mathbb{R}^n.$ Then,

$$
\mathbf{x} =
\begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n \\
\end{bmatrix}
, \; \text{and}  \;
\mathbf{y} =
\begin{bmatrix}
y_1 \\
y_2 \\
\vdots \\
y_n \\
\end{bmatrix}
$$

with the transpose of $\mathbf{x},$ given by the row vector $\mathbf{x}^T = \begin{bmatrix}x_1 & \ldots & x_n \end{bmatrix} .$

So,

$$
\mathbf{x} \cdot \mathbf{y} = \mathbf{x}^T \mathbf{y} =
\begin{bmatrix}
x_1 & x_2 & \ldots & x_n \\
\end{bmatrix}
\begin{bmatrix}
y_1 \\
y_2 \\
\vdots \\
y_n \\
\end{bmatrix}
$$


In [7]:
# dot product as a matrix product
# Note, we are putting the single [] version of x into the array command, so that we have a matrix 2D array structure with double [[]].
a = np.array([x])
print(a)
print("")

a = a.T
print(a)
print("")

b = np.array([y])
print(b)
print("")

b = b.T
print(b)
print("")

# recall we use @ for a matrix product
print(a.T)
print("")
print(b)
a.T@b

[[0 1 2]]

[[0]
 [1]
 [2]]

[[3 4 5]]

[[3]
 [4]
 [5]]

[[0 1 2]]

[[3]
 [4]
 [5]]


array([[14]])

### Length in $\mathbb{R}^n$

The length of a vector $\mathbf{x}$ in $\mathbb{R}^n$ is denoted by a 'double' absolute value symbol, $\left\lVert \mathbf{x} \right\rVert$.  The length of $\mathbf{x}$ is defined via the Pythagorean theorem as the square root of the dot product of $\mathbf{x}$ with itself, i.e.

$$\left\lVert \mathbf{x} \right\rVert  = \sqrt{\mathbf{x} \cdot \mathbf{x}}.$$

We also call this the norm of $\mathbf{x}.$ There are many norms. Specifically the just defined is also called the 2-norm or Euclidean norm.

Since the Euclidean norm is defined as dot product it shares similar properties:
1. $\left\lVert a\mathbf{x} \right\rVert = |a| \left\lVert \mathbf{x} \right\rVert$
2. $\left\lVert \mathbf{x}+\mathbf{y} \right\rVert \leq \left\lVert \mathbf{x} \right\rVert + \left\lVert \mathbf{y} \right\rVert,  \quad \quad$ (triangle inequality)
3. If $\left\lVert \mathbf{x} \right\rVert = 0$ then $ \mathbf{x} = \mathbf{0}, \quad \quad \; \;$ (This says that the zero vector is the only vector with norm 0.)

One can verify these properties directly from the definition.

In [9]:
# Three different commands to find the length of x

# taking square root of dot product using np.inner(x,x)
x_len1 = np.sqrt(np.inner(x,x))
print(x_len1)
print("")

# taking square root of dot product using matrix product row times column
x_len2 = np.sqrt(a.T@a)
print(x_len2)
print("")

# using built functionality of norm
x_len3 = np.linalg.norm(x)
print(x_len3)

2.23606797749979

[[2.23606798]]

2.23606797749979


In [15]:
# Optional: write code to find the length of y
y_len1 = np.sqrt(np.inner(y,y))
print(y_len1)

7.0710678118654755


In [17]:
# example of pulling a column or row vector directly from a matrix

# define matrix A
A = np.arange(9).reshape(3,3)+1
print(A)
print("")

# Recall how we can get the 1st col
print(A[:,0])
print("")

# length of 1st col of A
print(np.sqrt(np.inner(A[:,0],A[:,0])))
print("")

# better, just use the norm function
print(np.linalg.norm(A[:,0]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 4 7]

8.12403840463596

8.12403840463596


In [21]:
# Which col or row of A is `longest`? i.e. which has the greatest magnitude?
# You should not need a calculation to answer
# But calculate anyway to check
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))
print(np.linalg.norm(A[:,2]))
# Put your code here to check


8.12403840463596
9.643650760992955
11.224972160321824


In [ ]:
# Code to do all cols at one time
# axis calls rows with 1st dim matching our A.shape command
# returns a vector of norms for each vector along the specified axis

# cols one at a time
print(np.linalg.norm(A, axis=0))
print("")

# rows at one time
print(np.linalg.norm(A, axis=1))

# Does this match your calculations above??

### Angles in $\mathbb{R}^n$

In $\mathbb{R}^2$ and $\mathbb{R}^3$ we can visualize the angle $\theta$ between vectors and even find $\theta$ using the law of cosines. It's tough to visulize angles in $\mathbb{R}^n$ for $n\geq 4,$ but we can still generalize the idea of $\cos\theta$ in the same way we generalized the Pythagorean theorem in our definition of the Euclidean norm.

The cosine of the angle between vectors $\mathbf{x}$ and $\mathbf{y}$ in $\mathbb{R}^n$ is given by

$$ \cos \theta = \frac{\mathbf{x}\cdot\mathbf{y}}{\lVert \mathbf{x} \rVert \lVert \mathbf{y} \rVert}. $$


This is a nice idea, but we really are just interested in one angle between vectors in $\mathbb{R}^n$. What do think that angle is?

### Orthogonality

In $\mathbb{R}^2$ and $\mathbb{R}^3,$ we say that two vectors are perpendicular if the angle between them is 90 degrees or $\pi /2$ radians. Recall from trigonometry that the cosine of $\pi/2$ is zero.

In [ ]:
# We can even check this quickly with some code.
np.cos(90)

In [ ]:
# wait a second...
# input is probably radians. We always check any function in code cell
# or on the command line by typing ? in front of the function and running the cell
#  ?np.cos()
np.cos(np.pi/2)

# Wait again?? Isn't the result supposd to be zero?
# Numerically it is. Any number at 10^(-16) or thereabouts is numerically zero.

So from our generalization of the cosine formula, we only need to consider the numerator of that expression to find when two vectors are perpendicular in $\mathbb{R}^n.$ 

In fact we define two vectors $\mathbf{x}$ and $\mathbf{y}$ in $\mathbb{R}^n$ as being perpendicular, or *orthogonal*, if their dot product is zero. That is to say $\mathbf{x}$ and $\mathbf{y}$ are orthogonal, if $\mathbf{x} \cdot \mathbf{y} = 0.$ 

In symbols we write,

$$ \mathbf{x} \perp \mathbf{y}  \quad \quad \text{if} \quad \quad \mathbf{x} \cdot \mathbf{y} = 0. $$

### example

Consider the Haar matrix $H$, given by

$$
H = 
\begin{bmatrix}
1 & 1 & 1 & 1 \\
1 & 1 & -1 & -1 \\
1 & -1 & 1 & -1 \\
1 & -1 & -1 & 1 \\
\end{bmatrix}
$$

What are the angles between each column of $H$? Are the columns of $H$ orthogonal?

(Note that the rows are the same as the cols and the this matrix is *symmetric*.) How can you check or assess the orthogonality of the columns of $H$? Do this on scratch paper through calulation or decribe clearly in words.

In [ ]:
# Check your work using code examples from above.
H = np.array([[1, 1, 1, 1],[1, 1, -1, -1],[1, -1, 1, -1],[1, -1, -1, 1]])
H
#H[:,0].T@H[:,1] 
#np.inner(H[:,0], H[:,1])
H.T

In [ ]:
# Is there another way? Enter H as a matrix. 
# What do you get if you matrix multiply H with itself? What just happened?


In [ ]:
# How do we make the row and col vectors unit length?  Do this by scaling the matrix H appropriately.
# Then check each line by uncovering the # and rerunning the cell.

#G = (scalar)*H
#G
#G.T@G

### Some angle examples

Brief code examples shown.  Take notes on your own.

In [ ]:
np.degrees(np.arccos(0))

In [ ]:
np.degrees(np.pi/2)

In [ ]:
v = np.array([3, 2])
w = np.array([-1, 3])
v, w

######
# Uncover one at a time
np.dot(v, w)
np.linalg.norm(v)
np.linalg.norm(w)
angle = np.arccos(np.dot(v, w)/(np.linalg.norm(v)*np.linalg.norm(w)))
np.degrees(angle)


In [ ]:
x = np.array([-2, 3])
np.dot(v, x)