# Eigenvalues and eigenvectors

Our matrix equation $A \mathbf{x}= \mathbf{b}$ represents a linear tranformation of vector spaces.  

When $A$ is an $m \times n$ matrix, $A$ maps vector $\mathbf{x} \in \mathbb{R}^n$ to vector $\mathbf{b} \in \mathbb{R}^m.$ 
If $A$ is a square matrix with $n$ rows and $n$ columns, then $A$ maps $\mathbb{R}^n$ into $\mathbb{R}^n.$ 

Are there are any nonzero vectors whose 'direction' does not change after matrix multiplication by $A?$ 

Algebraically, we consider vectors that are scalar multiples of themselves under matrix multiplication by $A$ represented by the matrix equation

$$A\mathbf{x}=\lambda \textbf{x}.$$


Any $\lambda$ and associated nonzero vector(s) $\mathbf{x}$ that satisfy this equation are called *eigenvalues* and *eigenvectors* of $A.$ Note that eigenvectors are always associated with a particular $\lambda,$ and eigenvectors are nonzero vectors by definition.

### Nullspace of $ A -\lambda I $

Moving $\lambda \mathbf{x}$ to the left side of the equation above gives $A\mathbf{x}-\lambda \mathbf{x}  = \mathbf{0}.$ 

Continuing by multiplying by the $ n \times n$ identity matrix $I$ appropriately and factoring out the vector $\mathbf{x}$ turns the definition for eigenvalues and eigenvectors into a nullspace problem for the matrix $A-\lambda I$ as follows,  

$$ 
\begin{align*}
A\mathbf{x}-\lambda \mathbf{x}  & = \mathbf{0}, \\
A \mathbf{x} - \lambda I \mathbf{x} & = \mathbf{0}, \\
(A-\lambda I)\mathbf{x}  & = \mathbf{0}.
\end{align*}
$$


Eigenvectors of $A$ are in the nullspace of the matrix $A-\lambda I.$  

If the determinant of $A-\lambda I$ is zero, then this matrix is *singular*, (not invertible,) and we have a nontrivial nullspace (i.e. the nullspace is not just the zero vector.)  

When the dimension of $\text{Null}(A-\lambda I)$ is $n,$ we can find $n$ independent eigenvectors of $A$ giving an *eigenbasis* for $\mathbb{R}^n.$

### Finding eigenvalues and eigenvectors

To find the eigenvalues of $A,$ we form the matrix $A-\lambda I$ and consider the values $\lambda$ that make $\det(A-\lambda I)=0.$

Let
$A=\begin{bmatrix} 
.8 & .3 \\ 
.2 & .7 \end{bmatrix}.
$ 


Then $(A-\lambda I)=
\begin{bmatrix} 
.8-\lambda & .3 \\ 
.2 & .7-\lambda 
\end{bmatrix},$ 

with 

$$
\begin{align*}
\det (A-\lambda I) & = (.8-\lambda) (.7-\lambda) - (.3)(.2)\\
& =  0.56 - 1.5\lambda + \lambda^2 - 0.06 \\
& = \lambda^2 - 1.5 \lambda + 0.5 \\
& = ( \lambda - 1 ) (\lambda - 0.5).
\end{align*}
$$


We call $\det (A-\lambda I) = 0 $ the *characteristic equation*. Solving for the $\lambda$'s which make  $\displaystyle{\det (A-\lambda I) = 0}$ is the same as finding the roots of the characteristic equation.  

Here we have two distinct eigenvalues $\lambda_1 = 1$ and $\lambda_2 = \frac{1}{2}.$


---
#### Question 1

Finding eigenvectors associated with eigenvalues $\lambda_1 = 1$ and $\lambda_2 = \frac{1}{2}$, is done by finding vectors in the nullspaces of $(A-\lambda_1 I)$ and $(A-\lambda_2 I)$ respectively.

For $A$ listed in our example above, find eigenvectors associated with eigenvalues $\lambda_1 = 1$ and $\lambda_2 = \frac{1}{2}.$ Do this by hand and list your eigenvectors in the answer box below.


>
>Please write up your answer here.
>
> [.8-1  .3]
> [.2  .7-1]
>
> [-.2  .3]
> [.2  -.3]



---
### Code

The following code cells demo the $\texttt{np.linalg.eig()}$ command.


In [7]:
import numpy as np
from sympy import Matrix

In [8]:
# Input matrix A
A = np.array([[.8, .3],
              [.2, .7]])

print("The matrix A is\n", A, "\n")

# the linalg.eig() command will return a vector d containing eigenvalues, and a matrix V with associated
# unit length eigenvectors of A as cols of V

d, V = np.linalg.eig(A)

print("The eigenvalues of A are", d, "\n")

# Make the diagonal matrix D with eigenvalues of A on the diagonal.
D = np.diag(d)
print("The diagonal eigenvalue matrix Lambda is\n", D, "\n")
print("The eigenvector matrix V is\n", V, "\n")

The matrix A is
 [[0.8 0.3]
 [0.2 0.7]] 

The eigenvalues of A are [1.  0.5] 

The diagonal eigenvalue matrix Lambda is
 [[1.  0. ]
 [0.  0.5]] 

The eigenvector matrix V is
 [[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]] 



In [11]:
# Note that eigenvectors are normalized so that they are unit vectors, (length = 1).
# take x as an eigenvector we found by hand, and divide by its length (done for you.)

x = np.array([[3/2],
              [1]])

print("The vector x is \n", x,  "\n")
print("The length of x is", np.linalg.norm(x), "\n")

#x1 is a unit vector in the same direction as x
x1 = x/(np.linalg.norm(x))
print("x1 is a unit vector in the direction of x \n", 
      x1, "\n")

# What does A@x give us? Is this what we expect based on the theory?
print("The matrix product Ax is the vector\n", A@x, "\n")

The vector x is 
 [[1.5]
 [1. ]] 

The length of x is 1.8027756377319946 

x1 is a unit vector in the direction of x 
 [[0.83205029]
 [0.5547002 ]] 

The matrix product Ax is the vector
 [[1.5]
 [1. ]] 



In [13]:
# Check length calculation using (Pythagoras, dot product) of the eigenvector you found by hand. 
# Values may vary based on your x.
np.sqrt( x.T@x )#[0]#[0]

array([[1.80277564]])

---
#### Question 2

How do the eigenvalues and associated eigenvectors compare to what you found by hand?  Comment briefly.


>
>Please write up your answer here.
> The vector that we get by computer when divided by np.linalg.norm(the_vector) gives what we get by doing it by doing it by hand.
> Computer gives the unit vector which is just the unstretched version of what is calculated by hand.
>They are on the same line.


---
### Diagonalization

Suppose that the $n \times n$ matrix $A,$ has $n$ linearly independent eigenvectors $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n,$ and let $V$ be a matrix whose columns are $n$ linearly independent eigenvectors of $A$.   

Then, $V^{-1}AV$ will be a diagonal matrix, $D,$ with diagonal entries consisting of the eigenvalues of $A.$ 

In this case, we say that $A$ is *diagonalizable*, or $A$ is *diagonalized* by $V.$

This also implies that $A=VDV^{-1},$ which we can use to compute $k^{\text{th}}$ powers of $A.$ 

For large matrices it is much more efficient to compute powers of the diagonal matrix $D$ followed by two matrix products, than it would be to compute $A^k$ directly using $(k-1)$ matrix products.

First note that for $D=\begin{bmatrix} \lambda_1 & & \\ & \ddots & \\ && \lambda_n \end{bmatrix}, \quad D^k=\begin{bmatrix} \lambda_1^k & & \\ & \ddots & \\ && \lambda_n^k \end{bmatrix}. \quad \quad$  

---
#### Question 3

Why does $D^k$ have powers of the eigenvalues along the diagonal?  Explain in terms of your understanding of matrix products.

>
> The rest of the values except the ones in the diagonal are 0s. Therefore when we increase the power, we are just finding the dot product of matrix with the previous power. Therefore the power of eigenvalues along the diagonal increases in the exponent of k.
>


---
#### Matrix powers

Second, note that squaring $A$ using its diagonalization, $\left( V D V^{-1} \right),$ 

gives

$$
\begin{align*}
A^2 & = \left( V D V^{-1} \right) \left( V D V^{-1} \right ) \\
& = V D \left( V^{-1} V \right) D V^{-1} \\
& = V D \left( I_n \right) D V^{-1} \\
& = V D^2 V^{-1}.
\end{align*}
$$

In general, we have $A^k = VD^kV^{-1}.$

Answer the following questions first. Then compute powers of $A$ using the code given, and compare with what you thought was going to happen.


---
#### Question 4

What is the limit of $A^k$ as $k\rightarrow \infty?$ How can we determine this limit from the diagonalization of $A?$ Explain based on the discussion above, and then check using the code below. What do you find?

>
> As k goes to infinity:
>
> A = V D V^(-1)

> A^2 = V D^2 V^(-1)

> A^3 = V D^3 V^(-1)

> ...
>

> When we change the k below to larger and larger, the output gets smaller. The 1 stays intact showing the start of the diagonal matrix. Thus when k gets to infinity, the limit of A^k goes to 0.


In [20]:
# For a 2x2 matrix powers are not that bad, but for large nxn matrices we would want to do something different
# Compare computing A^2 with using our diagonalization from above.

# Adjust k to find various powers of A^k.  What matrix does A^k approach for large k?
k = 100
print(np.linalg.matrix_power(A, k), "\n")

# Diagonalization
print(np.linalg.matrix_power(D, k), "\n")

print(V@(np.linalg.matrix_power(D, k))@np.linalg.inv(V))

[[0.6 0.6]
 [0.4 0.4]] 

[[1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 7.88860905e-31]] 

[[0.6 0.6]
 [0.4 0.4]]


In [22]:
# Another Markov example
A = np.array([[.8, .6],
              [.2, .4]])
A

array([[0.8, 0.6],
       [0.2, 0.4]])

In [49]:
# Check for different powers k.
k = 1
print("K = 1")
print(np.linalg.matrix_power(A, k))

print("\nK = 1000")
k = 1000
print(np.linalg.matrix_power(A, k))

K = 1
[[0.8 0.6]
 [0.2 0.4]]

K = 1000
[[0.75 0.75]
 [0.25 0.25]]
