# Matrix operations

### Matrix addition and scalar multiplication

Vectors and matrices (plural of matrix) are arrays of numbers, and the main objects of interest in linear algebra. A matrix is a 2D array consisting of *m* rows and *n* columns. Our convention will always be to list rows first, and columns second (conveniently matching the convention in Python.) Vectors will always be assumed to be column vectors, unless otherwise stated.

We can add any two matrices, $A$ and $B,$ (or vectors) together as long as they have the same shape, meaning the same number of rows and columns. In this case the addition is entry wise, so that the numbers in the same positions in each matrix are added to together, giving the sum of the two entries as the value in the same position in resulting matrix sum.

Let $A =
\begin{bmatrix}
a & b \\
c & d \\
\end{bmatrix}
$ and
$
B=
\begin{bmatrix}
e & f \\
g & h \\
\end{bmatrix}
.$
Then $A + B =
\begin{bmatrix}
a+e & b+f \\
c+g & d+h \\
\end{bmatrix}
.$

Scalar multiplication works the same way for matrices and vectors, and is an entry-wise multiplcation.  

Using the matrix $A$ again from above, 

$$
3A \; = \;
3\begin{bmatrix}
a & b \\
c & d \\
\end{bmatrix}
\;=\;
\begin{bmatrix}
3a & 3b \\
3c & 3d \\
\end{bmatrix}.
$$

Note, we have to be careful with the word dimensions and dimension.  The English word *dimensions* refers to the shape of a matrix, number of rows and columns. *Dimension* has a different meaning in linear algebraic terms, typically referring to the length of a vector or denoting the number of *linearly independent* rows or columns in a matrix, or set of vectors. Be aware of this distinction when reading from different sources. We can always use shape to avoid confusion when talking about the number of rows and columns of a matrix if needed. Shape is also used as the command in Python to determine the number of rows and columns of an array.


#### An example 

Define a $3 \times 4$ matrix $A$ as 

$$
A=
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix}
.$$

For individual entries we use $a_{i,j}$ (or just $a_{ij}$) to indicate the number in the *i*th row and *j*th column of $A.$ 


If we consider $A$ in terms of its column vectors, $\textbf{v}_1, \dots, \textbf{v}_n,$ then we write the *j*th column of $A$ as $\textbf{v}_j.$ 

Python uses zero-based indexing which means each index starts counting from zero. We typically start counting from one. We just need to remember this difference in convention from what is written in our notes describing entries of $A$ using $a_{ij}$ versus our Python code for the *(i+1)*th row and *(j+1)*th column matrix entry given by `A[i,j]` where $i$ and $j$ range between 0 and $n-1$ instead of 1 to $n.$ Note, for column vectors of $A,$ we then have $\textbf{v}_{j+1},$ given by `A[:,j]` respectively for an entry or vector from the array. 

We can also represent vectors as 'tuples.' Note, a tuple is both a data type in Python and also a linear algebra term. Usage always depends on context. Unless otherwise stated, we are using terms in the linear algebra sense. So $\textbf{v}_{1}$ as a triple, i.e. 3-tuple, is written as $\textbf{v}_{1} = (1, 5, 9),$ matching the corresponding 3-space coordinates of the vector. 

Writing column vectors as tuples has the advantage of saving space in our written document. Always ask questions on notation sooner than later to clear up confusion. 'Fixing' notation is important so we have the same conventions and the same starting point for communicating and describing these objects. There is not a single standard or convention, so be careful when using other resources.

Also, be careful with indexing. Your book and other resources usually start counting at 1.  When using and writing Python we count starting at zero. There is nothing extra to do here, just remember that Python uses zero-based indexing.

In [2]:
# Load packages, run this
import numpy as np
from sympy import Matrix

---
### Your turn

Write Python code in the cell below to find the third column $\textbf{v}_3 = (3, 7, 11)$ and the 2nd row $(5, 6, 7, 8)$ of the matrix $A.$ Verify it works.

(Code provided to define $A$.)



In [4]:
# Your turn
A = np.arange(12).reshape(3,4)+1
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
v3 = A[:,2]
v3

array([ 3,  7, 11])

In [13]:
r2 = A[1,:]
r2

array([5, 6, 7, 8])

---

### Matrix-vector multiplication

#### Column view

The column view of a matrix-vector multiplication is particularly useful for understanding matrix multiplication as a linear combination of the columns of $A.$

In general, for 

$A = [\textbf{v}_1 \; \textbf{v}_2 \; \ldots \; \textbf{v}_n],$ 

and 

$\textbf{x} =
\begin{bmatrix}
x_1 \\ \vdots \\ x_n
\end{bmatrix},
$

We define the matrix-vector multiplication as the linear combination of the columns of $A$ given by

$$ A\textbf{x} \; = \; x_1 \textbf{v}_1 + x_2 \textbf{v}_2 + \ldots + x_n \textbf{v}_n .$$

#### Matrix-vector multiplication example


Let

$
A=
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix}
\quad \textrm{and} \quad
\textbf{x} = 
\begin{bmatrix}
1 \\ 1 \\ 1 \\ -2
\end{bmatrix}.
$

By our definition, $A\textbf{x}$ is a linear combination of the columns of $A$ with scalar coefficients coming from the entries of $\textbf{x}$ given by,

$ A\textbf{x} = 
(1)\begin{bmatrix}
1 \\ 5 \\ 9 
\end{bmatrix}
+
(1)\begin{bmatrix}
2 \\ 6 \\ 10 
\end{bmatrix}
+
(1)\begin{bmatrix}
3 \\ 7 \\ 11 
\end{bmatrix}
+
(-2)\begin{bmatrix}
4 \\ 8 \\ 12 
\end{bmatrix}.
$

Do by hand and then check using the code below.

In [15]:
# using our previously defined A and x
# note the shapes here, x is entered as a 1D array
x = np.array([1, 1, 1, -2])
answer = x[0]*A[:,0] + x[1]*A[:,1] + x[2]*A[:,2] + x[3]*A[:,3] 
answer

array([-2,  2,  6])

---

### Another example (revisited)

Here is an example used in the Gaussian elimination notebook, where we
consider the system of linear equations

$\begin{align}
x_1-2x_2 & = 1 \\
3x_1+2x_2 & = 11 \\
\end{align}.$

This system is given by the matrix equation $A\textbf{x}=\textbf{b}$ where

$
A =
\begin{bmatrix}
1 & -2 \\
3 & 2
\end{bmatrix}, \;
\textbf{x} =
\begin{bmatrix}
x_1 \\
x_2
\end{bmatrix},
\; \text{and,} \;
\textbf{b} =
\begin{bmatrix}
1 \\
11
\end{bmatrix}.
$

We can view the matrix product of $A\textbf{x}$ as a linear combination of the columns of $A$ with scalar coefficients $x_1$ and $x_2,$ 

$x_1\begin{bmatrix}1 \\ 3 \end{bmatrix} + x_2\begin{bmatrix} -2 \\ 2 \end{bmatrix}.$ 

Solving the system is the same as finding a *linear combination* of the columns of $A$ that equal $\textbf{b}.$ 

Find the solution by hand and then check with code below.

In [17]:
## example revisited
A = np.array([[1, -2],[3, 2]]) # enter A by hand
x = np.array([[3],[1]]) # enter x as a 2D column vector

print("A = ")
print(A)
print("")
print("x = ")
print(x)
print("")

# run cell multiple times, uncovering #'s' one at a time to see what is happening
#x[0]*A[:,0]
#x[1]
#x[1]*A[:,1]
#x[0]*A[:,0] + x[1]*A[:,1]


A = 
[[ 1 -2]
 [ 3  2]]

x = 
[[3]
 [1]]



---
### Your turn

(This is Activity 2.2.2a from Understanding Linear Algebra (ULA) by David Austin at Grand Valley State University.)

Use the column view of matrix-vector multiplication to calculate the product below.

$
A=
\begin{bmatrix}
1 & 2 & 0 & -1 \\
2 & 4 & -3 & -2 \\
-1 & -2 & 6 & 1
\end{bmatrix}
\quad \textrm{and} \quad
\textbf{x} = 
\begin{bmatrix}
3 \\ 1 \\ -1 \\ 1
\end{bmatrix}.
$

Do by hand and then check with your code in the cell below.

In [21]:
# Your code here
# enter A as a 2D array
A = np.array([[1, 2, 0, -1],[2, 4, -3, -2],[-1, -2, 6, 1]])
print(A)

print("")

# enter x as 1D
x = np.array([3, 1, -1, 1])
print(x)

print("")



# what we did in class using linear combinations of columns of A
# note our output is only 1D even though mathematically
# we consider this a column vector. 
# Also note, Ax on the left is a name not a computation.

A_x = x[0]*A[:,0] + x[1]*A[:,1] + x[2]*A[:,2] + x[3]*A[:,3]
print(A_x)

### next lines implement the @ operator for matrix multiplication in numpy.
## Note that we need our vector x as 2D array here and we have two brackets, [[]]. Why?
#x = np.array([x]).T
#x.shape
#A@x

[[ 1  2  0 -1]
 [ 2  4 -3 -2]
 [-1 -2  6  1]]

[ 3  1 -1  1]

[  4  11 -10]


---
### Row view

Using our column view definition, we can rearrange the multiplications and addtitions using distributivity to come up with an alternate row view of a matrix-vector product.  

Under the row view, the $i$-th entry of the product is the $i$-th row of $A$ multiplied by $\textbf{x},$

$$
\begin{bmatrix} a_{i1} & a_{i2} & \dots & a_{in} \end{bmatrix} 
\begin{bmatrix}
x_1 \\ x_2 \\ \vdots \\ x_n
\end{bmatrix}.
$$

Using the column view definition we treat an individual row as a $1 \times n$ matrix, so that the $i$-th entry of the product, $A\textbf{x}_i,$

is given by 

$$ \left(A\textbf{x}\right)_i \; = \; x_1 a_{i1} + x_2 a_{i2} + \ldots + x_n a_{in} \; =\; \sum_{k=1}^n a_{ik}x_k. $$

This "row-column" matrix multiplication is called the "dot" product.  It is a convenient convention to produce individual matrix product entries. The dot product of two vectors from $\mathbb{R}^n$ also has important geometric properties that we use to define the length of an single vector and the "angle" between two vectors. (See dot product notes.)


---
### Matrix-matrix multiplication

We can extend the column view and row view of matrix-vector multiplication to define matrix-matrix multiplication. 

Let $A$ be a $m \times n$ matrix. This indicates that $A$ has $m$ rows and $n$ columns, and let $B$ be a $n \times p$ matrix. This indicates that $B$ has $n$ rows and $p$ columns.

We can define the matrix product of $A$ and $B$, $AB,$ when the number of columns of $A$ is the same as the number of rows of $B.$ This means that a row of $A$ has the same number of entries as a column of $B.$

First note that in order for a matrix product to make sense, the number of rows for the matrix on the right of the product, must match the number of columns of the matrix on the left of the product. The product $AB$ will be an $m \times p$ matrix.

Let $\textbf{v}_1, \; \textbf{v}_2, \; \ldots, \; \textbf{v}_n$ be the columns of $A,$ so that 

$A = [\textbf{v}_1 \; \textbf{v}_2 \; \ldots \; \textbf{v}_n],$ and

let $\textbf{w}_1, \; \textbf{w}_2, \; \ldots, \; \textbf{w}_p$ be the columns of $B,$ so that 

$B = [\textbf{w}_1 \; \textbf{w}_2 \; \ldots \; \textbf{w}_p].$

Also note that $\textbf{v}_k \in \mathbb{R}^m$ for $k$ ranging from $1$ to $n,$ and $\textbf{w}_l \in \mathbb{R}^n$ for $l$ ranging from $1$ to $p.$

Using the the previous matrix-vector definitions as a guide we get the following matrix-matrix multiplication definitions:
1. Column view $$AB = [A\textbf{w}_1 \ A\textbf{w}_2  \ \ldots \  A\textbf{w}_p],$$
2. Row view $$ \left(AB\right)_{ij} \; = \; a_{i1} b_{1j} + a_{i2} b_{2j} + \ldots + a_{in} b_{nj} \; =\;  \sum_{k=1}^n a_{ik} b_{kj}. $$


In words, the column view and row view of matrix multiplication can be described as
1. The columns of the matrix product, $AB,$ are the matrix-vector products of $A$ with the columns of $B$ respectively, and
2. The $ij$-th entry of the matrix product, $AB,$ is matrix-vector product of the $i$-th row of $A$ with the $j$-th column of $B,$  $$ \left(AB\right)_{ij} \; = \; (\text{Row} \; i) \cdot (\text{Col} \; j). $$


---
### numpy @ for matrix multiplication

Fortunately, there is a convenient numpy operator for matrix multiplication using the `@` symbol that will perform matrix multiplication. The "shapes" (dimensions) of the matrices must match for this operation to make sense.  Again, for any matrix-vector (or matrix-matrix) product to make sense, the number of columns of the left matrix, mus match the number of rows of the right matrix.

For our previous examples we would use `A@x` for $A\textbf{x}.$

See the code example below, and try on your previous examples.

In [ ]:
# example revisited using matrix operator @
# make sure both are 2D arrays and that the cols of A are the same as the rows of B (x in this example.)
A = np.array([[1, -2],[3, 2]]) # enter A by hand
x = np.array([[3],[1]]) # enter x as a 2D column vector
A@x

---
### Your turn 

(Activity 2.2.2a from ULA using matrix products)

Repeat, using the row view of matrix-vector mulitplication to enter and find the first entry of the product for Activity 2.2.2 part a from the example above.

Put your code in the cell below and verify you get the same result as your linear combination of columns calculation.

In [ ]:
# your code here using @ for with a row view.
A = np.array([[1, 2, 0, -1],[2, 4, -3, -2],[-1, -2, 6, 1]])
print(A)
print("")

# enter x as before as 1D
x = np.array([3, 1, -1, 1])
print(x)
print("")

# @ recognizes what to do in this case but outputs 1D answer like before
# put your code here


In [ ]:
# Make x 2D as 4x1 column vector / (matrix)
A = np.array([[1, 2, 0, -1],[2, 4, -3, -2],[-1, -2, 6, 1]])
print(A)
print("")

# enter x as 2D this time as a row with 2 sets of [[]], and take transpose.
x = np.array([[3, 1, -1, 1]]).T
print(x)
print("")

# Output is 2D column vector.
# Pay attention to shape.

#print(A@x)
print("")
#(A@x).shape

---
### Your turn, More practice

Do more.  Do by hand and check with Python. Add markdown cells and comment as needed.


In [ ]:
#Note matrix multiplication is not commutative!!
A = np.array([[1, 2], [3, 4]])
B = np.array([[7, 9], [5, 8]])
print(A)
print(B)
print(A@B)
B@A