# Getting started with arrays in NumPy

The objects of interest in linear algebra are vectors and matrices. Python is used widely in numerical and scientific computing, and data science. NumPy is the standard Python library for computing with arrays (matrices/vectors). We briefly cover some commands to start working with arrays in NumPy. 

Check out the NumPy website at [numpy.org](https://www.numpy.org).

In [22]:
#standard numpy import and abbreviation
import numpy as np

### NumPy and the N-dimensional array

The **dimension** (of a vector space) in linear algebra is defined as the number of vectors in a basis. Dimension for the N-dimensional array in NumPy is also the *shape* of the array, and gives the number of rows and columns as a tuple, `(row, col)`. 

**Shape** may be a better term to use to avoid confusion with the vector space definition of dimension, when describing the number of rows and columns of a matrix. Context matters! When talking about the dimension of the axes, rows and columns, we use the `.shape` command/extension to get this information. Remember that the dimension of a vector space is a specific definition in describing the number of vectors in a basis.

The `numpy.array()` command accepts lists (or tuples), and lists of lists, as input. Notice we imported the `numpy` library as `np`.

Square brackets, `[]`, are used for lists, and regular parethenses, `()`, are used for tuples in Python. We use these groupings in the input of the array command to define vectors and matrices in Python.

Let's get started with an example in the following code cell. Read the comments as well as the code!

In [70]:
# hashtags in code cells indicate a "comment." Commented lines are not recognized as code.
# Here we enter a vector, b, as a single list using a sinlge set of square brackets.
# The vector b is a 1-D array in NumPy.
b = np.array([1, 11])

### uncomment each of the following lines one at a time, and rerun the cell.  What do you notice?

b
type(b)
b.shape

print(b) #compare this printed output to the view when b is the last line. 
b

[ 1 11]


array([ 1, 11])


---
#### Question 1

In the code cell above, remove the hashtags (comment symbols) one at a time. Rerun the cell using shift+enter after hashtag removal.  

What do you notice after each run?  Comment and take notes in the block quote here.

>
> Comment here.
>
---


In [86]:
# This code cell shows how we enter a matrix as a 2-D array in Python.

A = np.array([
        [1, -2],
        [3, 2],
    ])
A

# uncomment each of the following lines one at a time, and rerun the cell.  What do you notice?

type(A)
print(A.shape)
print(A)
print(type(A))
A

(2, 2)
[[ 1 -2]
 [ 3  2]]
<class 'numpy.ndarray'>


array([[ 1, -2],
       [ 3,  2]])

---
#### Question 2

In the code cell above, remove the hashtags (comment symbol) one at a time. Rerun the cell after each removal.  

What do you notice after each run?  Comment and take notes in the block quote here. Is there anything you see here that you missed in the previous question?

>
> Comment here.
>
---


### Shape, indexing, and concatenation 

shape, rows, cols, shape, indexing zero-based, vectors in Python as 1-d vs 2-d objects

Concatenation commands require the same array dimension, and "shape" along the specified axis where we are "gluing" them together.  Specifically, most concatenation commands require that we have two 2-D arrays to combine. 

Often, we may want to augment a matrix with additional column vector(s), as is the case when solving a linear system using row reduction. This happens frequently enough that there is a special command, `np.column_stack()` for this purpose.

Recall, a matrix is a 2-D array in NumPy, and a vector is only a 1-D array.


In [94]:
# Consider the matrix from above augmented with b as a third column vector.
# Using column_stack, augment the 2x2 matrix A, a 2-dimensional object in Python,
# with the vector b which is 1-dimensional.  Recall the shape of A and b.  
#
# Most concatenation commands require that the "shapes" are the same between the objects, 
# column stack allows us to add a 1-D vector to a 2-D matrix as long as 
# the number of entries in the vector match the number of rows (first dimension) in the matrix.

Aug_Ab = np.column_stack((A,b))
Aug_Ab

array([[ 1, -2,  1],
       [ 3,  2, 11]])

We can access particular entries in a matrix or vector by giving the index of the entry we want inside of square brackets after the matrix, such as `A[1,2]`. `A[1,2]` is **not** the first row and second column entry of this matrix. It is actually the second row, third column entry since Python uses **zero-based indexing**.  We start counting at zero, not one.

The case for "[Why numbering should start at zero](https://www.cs.utexas.edu/users/EWD/transcriptions/EWD08xx/EWD831.html)" by Edsger W. Dijkstra.

Starting at zero for counting our indices using `A[row, col]` gives the desired entry.

This will even work for entire rows or columns, using **slicing** by putting a colon, `:`, in the row or column position of the command.

See the examples in the code cells below.

In [98]:
# arange gives integers from the starting value of 0 up to, but not including, the integer input.
# input of 12 gives 12 entries in a the vector from 0 to 11.
AA = np.arange(12)
AA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [100]:
# reshape command, changes the shape into a 3 x 4 matrix.  
# Note that shape takes the actual "dimensions", where zero-based indexing is only for our indices
# indicating position in a vector or matrix.
AA = np.arange(12).reshape(3, 4)
AA

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

---
#### Question 3

1. Before running the code cell below, guess at what you think the output will (should) be.
2. Run the cell one at a time after removing each # to check yourself.  
3. Leave your original guesses whether right or wrong. Take notes for yourself that will help you when you reference back this notebook.

For each line of code listed in the comment block, do 1-3. Note anything new or special not previously mentioned.

>
> `AA[0,1]` is
> 1
> My guess was right/wrong. Comment further if needed.
>
>
> `AA[1,3]` is
> 7
> My guess was right/wrong. Comment further if needed.
>
>
> `AA[3,1]` is
> err
> My guess was right/wrong. Comment further if needed.
>
>
> `AA[2,1]` is
> 9
> My guess was right/wrong. Comment further if needed.
>
>
> `AA[:,2]` is
> `[2, 6, 10]`
> My guess was right/wrong. Comment further if needed.
>
>
> `AA[2,:]` is
> `[8, 9, 10, 11]`
> My guess was right/wrong. Comment further if needed.
>
---

In [116]:
# Guess first and note your guess above in the question cell.
# uncomment one line at a time and run the code cell to see the output.

AA[0,1]
AA[1,3]
#AA[3,1]
AA[2,1]
AA[:,2]
AA[2,:]

array([ 8,  9, 10, 11])

There are several concatenation commands that will prove useful, `np.hstack()`, `np.vstack()`, and `np.concatenate()`. The *h* and *v* stand for horizontal and vertical, and we are "stacking" arrays.  Most commands are named suggestively in this fashion.  If you can think of what you want to do with your code, usually a quick search with suggestive key words will get reasonable results. Use the "Google". The NumPy documentation can also be helpful, and you should try there first.

Concatentation using `np.concatenate()` allows you to designate the axis along which you are stacking the arrays. Remember we are using zero-based indexing to call the axis, (0 = row or 1 = col).

See code examples below.

In [118]:
# vertical stack, stacks rows
np.vstack((AA,AA))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
# horizontal stack, stacks columns
np.hstack((AA, AA))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [122]:
# concatenation along rows, stacks rows, same as vstack
np.concatenate((AA, AA), axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

The commands `hstack()` and `concatenate()` will not work on A and b, beacause they have different shapes. But putting the 1-D vector, b, into the array command inside square brackets, `np.array([b])` gives the desired result.

In [ ]:
# b_ is just a name, object we create, we name on the left of the equal sign
b_ = np.array([b])

# b_ has how many brackets? What is the shape?
b_

# uncomment as before to check out what happens with the following commands.
# What is the .T extension? It is a transpose.  What is it doing?

#b_transpose = b_.T
#b_transpose

---
#### Question 4

What is still confusing right now?  Take some notes for yourself here to look back at later.

We have covered most of what we need to get started working with matrices and vectors in Python using NumPy arrays. 

>
> Comment here. Take notes here.
>
---