# Google PageRank

A play on words, using the idea of ranking web pages on the world wide web along with the name of one of Google's founders, Larry Page.  Larry Page and Sergey Brin founded Google in the late 1990s (1998?) primarily as a search engine for information and websites on the internet.  Less than ten years later, as of 2005 each were worth more than \$10 billion dollars (US).

In the language of linear algebra, their ranking algorithm uses *transition* matrices and is a *Markov process*.  When all entries in a square matrix are real and positive, Perron's Theorem guarantees that the matrix has a unique eigenvector with all positive entries and the unique associated eigenvalue is the largest of all the eigenvalues of the matrix.  

In the case of the Google matrix (a Markov matrix) this largest eigenvalue is 1, and the associated eigenvector is the ranking vector.

Let's explore with an example.


### Markov processes - Transition matrix example 

Suppose each year 10\% of the people outside California move in, and 20\% of the people inside California move out.

Start with initial populations $y_0,$ outside of, and $z_0,$ inside of, California respectively. 

Then we get the transition matrix (of probabilities) given by,

$A = 
\begin{bmatrix} .9 & .2 \\ 
.1 & .8 
\end{bmatrix}$ with initial population vector 
$ \textbf{u}_0 = 
\begin{bmatrix} y_0  \\ 
z_0 
\end{bmatrix}.$

Each column sums to 1, indicating a constant total population equal to $y_0 + z_0.$

---
#### Question - Steady-state

No matter what population you start with for $y_0$ and $z_0,$ you will always approach the steady-state solution of two-thirds of the total population being outside of California and one-third inside.

Why? 

This is our central question, and the answer comes from the considering the the eigenvalues and associated eigenvectors of the transition matrix. It is a diagonalizable matrix. In the cells below you will implement code that uses matrix multiplication of the transition matrix with the population vector with yearly movements of people flowing into and out of California.  Each year represents multiplication by your transition matrix.  Answer the now with your initial thoughts, and again after you have run the code below.  Discuss in terms of the diagonalization of the transistion matrix.

>
> Please write up your answer here.
> When k approaches to the maximim limit for A^k, D^k->infi goes closer to [[1,0][0,0]].

> The eigen vectors obtained from the matrix A are [2,1] and [1,-1].

> When the eigen vectors are used in V . D . V^(-1), the resulting dot product equation will become [[2/3,2/3],[1/3,1/3]] [y0, z0]

> Which will ultimately give a dot product of [2/3(y0+z0),1/3(y0+z0)]

> Therefore no matter what two values we take, the output will be a steady-state solution because y0 & z0 are both added.




---
#### Implementation

Type in your transition matrix $A.$  

Set starting values for $y_0$ and $z_0$ (actual numbers you choose,) and see how many iterations it takes to reach your steady-state values to four decimal places. (How might you script/automate this code?)

Use `u = A@u` in the code cell below.

Do this until the decimals stop changing in 1/10000 place.  How long did it take?  Did your answer converge to the steady-state vector previously mentioned? How can you use diagonalization to find the steady-state?  Explain briefly.


In [1]:
import numpy as np

In [3]:
# (Semi-optional) We'll code as a class
# Put your code here. Try your own version first, before moving on.
# What about diagonalozation?

A = np.array([[.9, .2],
              [.1, .8]])
u = np.array([[40], 
              [305]]) 

for i in range(10):
    u = A@u

u

array([[224.63297027],
       [120.36702973]])

#### Try your own loop above first!

Before moving on to the code below, think about how you can automate the process. You will multiply the initial value vector $\textbf{u}_0$ by A to get the values at the next timestep $$\textbf{u}_1 \; = \; A\textbf{u}_0.$$

Iterating this process requires multiplication by $A$ at each step so that

$$\textbf{u}_{n+1} \; = \; A\textbf{u}_n.$$

In general, this means that 

$$\textbf{u}_{n+1} \; = \; A^n\textbf{u}_0.$$

When $A$ is diagonalizable we can use the diagonalization directly to find steady-states if they exist.

For now, try to write a working loop. We can compare our loops to the diagonalization method later.

In [5]:
# working code that automates the process.
A = np.array([[.9, .2], 
              [.1, .8]])

# choose starting values for the populations inside u[0] and outside u[1]
u = np.array([[40], 
              [305]])

# steady-state vector
print(np.sum(u) * np.array([[2/3], [1/3]]), "\n")

# np.linalg.eig() command
d, V = np.linalg.eig(A)

tol = 0.00001
diff = 1
k = 0

# use a while loop to implement the stopping condition
while diff >= tol:
    u1 = A@u
    # norm is a notion of "distance" between vectors
    diff = np.linalg.norm(u1 - u)
    u = u1
    k += 1
    # print(diff)
    
print(u, k)

[[230.]
 [115.]] 

[[229.99998577]
 [115.00001423]] 46


### Another example - (Preview 4.5.1 ULA)

Suppose that our rental car company rents from two locations P and Q. We find that 80% of the cars rented from location P are returned to P while the other 20% are returned to Q. For cars rented from location Q, 60% are returned to Q and 40% to P.

Use the example above to implement all parts of the preview activity here in this notebook.  Check your by hand calculations.

In [7]:
# This is the transition matrix we should have with a total of 1500 cars, all initially at P.
A = np.array([[.8, .4], 
              [.2, .6]])

x0 = np.array([[1500, 0]]).T

A, x0

(array([[0.8, 0.4],
        [0.2, 0.6]]),
 array([[1500],
        [   0]]))

In [9]:
d, V = np.linalg.eig(A)
print(d, "\n")

# Make the diagonal matrix D with eigenvalues of A on the diagonal.
D = np.diag(d)

print(D, "\n")
print(V, "\n")

[1.  0.4] 

[[1.  0. ]
 [0.  0.4]] 

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]] 



#### Question

What does diagonalization do for us in this case? Explain.

> Since the matrix we have is, diagonalizable we can use the diagonalization directly to find steady-states. 
> np.diag(d) gives us the output in the form of two column eigen vectors.

> If A - lam.I is [[a-lam b][c d-lam]], we can ignore b and c because we are multiplying with an identity matrix. therefore, A - lam is only considered.

In [11]:
# diagonaliztion of A**k, k large. Why?
V @ np.array([[1,0], [0,0]]) @ np.linalg.inv(V)

array([[0.66666667, 0.66666667],
       [0.33333333, 0.33333333]])

#### Question

Does it matter what your initial values are? How and why?

>
> It doesn't matter what the initial values are. Since we are adding the In and Out values, the multiplication with 2/3 and 1/3 will have the same ratio at the end.

> The eigen vectors obtained from the matrix A are [2,1] and [1,-1].

> When the eigen vectors are used in V . D . V^(-1), the resulting dot product equation will become [[2/3,2/3],[1/3,1/3]] [y0, z0]

> Which will ultimately give a dot product of [2/3(y0+z0),1/3(y0+z0)]

> Therefore no matter what two values we take, the output will be a steady-state solution because y0 & z0 are both added.




### PageRank example

Google models your web surfing assuming that everyone is a random surfer with "damping" conditions that guarantee Perron's Theorem (Perron-Froenius) can be used to rank every page on the internet.  They assume that if you start on a given page you have a 85% chance of following a link on that page, and a 15% of "teleporting" to any page in the network.

Consider the network in figure 10.4 on the top of page 98 in "When Life is Linear" (T. Chartier).  What is the Google matrix for this network?

Using the iterative process from the population example above, what is the ranking vector?  Does the page we start on matter in determining this vector?  Experiment and discuss on what you have done with your classmates.

The material in the book uses a left eigenvector (row vector.)  What can we do to use our notation with the right eigenvectors we have defined with the convention in our book?

Discuss as a group, and individually input your Markov matrix in the code cell below. Experiment. Answer the questions above and any others you come up with.  Discuss any interesting observations from your experimentation.



In [13]:
# Start with finding and defining the transition matrix on page 99. 
# Our matrix should be for right eigenvector so it will be different from the handout. (How?)

G = np.array([[1/40, 35/40, 35/40, 1/40, 1/40, 6/36],
    [1/40, 1/40, 1/40, 37/120, 1/40, 6/36],
    [1/40, 1/40, 1/40, 37/120, 18/40, 6/36],
    [35/40, 1/40, 1/40, 1/40, 1/40, 6/36],
    [1/40, 1/40, 1/40, 37/120, 1/40, 6/36],
    [1/40, 1/40, 1/40, 1/40, 18/40, 6/36]])

print(G)

[[0.025      0.875      0.875      0.025      0.025      0.16666667]
 [0.025      0.025      0.025      0.30833333 0.025      0.16666667]
 [0.025      0.025      0.025      0.30833333 0.45       0.16666667]
 [0.875      0.025      0.025      0.025      0.025      0.16666667]
 [0.025      0.025      0.025      0.30833333 0.025      0.16666667]
 [0.025      0.025      0.025      0.025      0.45       0.16666667]]


In [15]:
# Put your code here for the PageRank example.
v = np.array([[1, 0, 0, 0, 0, 0]]).T

#### Before moving on, try your own code first!

Try something in the code cell above before looking at the code below. Look back at previous examples for ideas!



In [17]:
# Try your own code first! Then check this out.

v = np.array([[1, 0, 0, 0, 0, 0]]).T

#v=G@v

tol = 0.0001;
dg = 1;
k = 0;

while dg >= tol:
    v1 = G@v
    dg = np.linalg.norm(v1-v)
    v = v1
    k = k+1

print(v, k)

[[0.26764086]
 [0.11192761]
 [0.15948778]
 [0.26447998]
 [0.11192761]
 [0.08453615]] 30


In [19]:
# Using diagonalization
d, V = np.linalg.eig(G)
print(d, "\n")

# ranking vector corresponds to steady-state 
# given by the eigenvector associated with eigenvalue = 1 (guaranteed by Perron Thm.)
v1 = V[:,0]
out = v1/sum(v1)
print(out, "\n")

[ 1.00000000e+00+0.j         -3.03658516e-01+0.64560393j
 -3.03658516e-01-0.64560393j -2.26683974e-01+0.j
  1.25667673e-01+0.j          1.70816868e-17+0.j        ] 

[0.26766152-0.j 0.11191508-0.j 0.15947899-0.j 0.26448886-0.j
 0.11191508-0.j 0.08454048-0.j] 



---
### (Your) Discussion of PageRank

Describe in your own words how the PageRank algorithm presented ranks web pages.

>
> My prediction was that node 3 and 1 would have the highest probability. However, we were correct on the 1, but not on the 3.

> We were correct on the node 6, since it had only one link coming to it, it had the least probability.
>
> This means that the page rankings are done by how many other pages link to the target webpage. I know this by SEO which is search engine optimization. In order make a page search engine optimized, we need to link our page to different other pages. This means that the algorithm is working as expected with only one outlier which may be caused because of any cycle that loops back to the same page. 
>