# Reduced row echelon form and linear (in)dependence

## Reduced row echelon form

Recall that we can put a matrix into reduced row echelon form (rref) through a series of elementary row operations. Effectively we are using linear combinations of the row of a matrix to make it *row-reduced*. 

What is needed for a matrix to be in reduced-row echelon form?
+ Any row that is not all zeros must start with a leading "1," called a pivot. Any row without a pivot must be all zeros and will come at the "bottom" of the matrix.
+ Pivots (leading 1's) must have zeros above and below in the same column of the matrix.
+ A pivot in a "higher" row must be to the "left" of a pivot in a "lower" row. This also implies that a pivot in a "lower" row must be to the "right" of a pivot in a "higher" row.
+ Again, any row without a pivot must be all zeros and will come at the "bottom" of the matrix.

We may use any row combinations needed to achieve the **rref** of a matrix. Generally this is accomplished by a sequence of elementary row operations moving the matrix to the form described by focusing on:
+ creating pivots from top left of the matrix (top rows, left cols) down to the right,
+ after getting a pivot, zeroing out below the pivot in the same column, one row at a time,
+ Once pivots (leading ones) are exhausted, then zero above the pivots starting in the rightmost pivot columns first,
+ and move back up to the left zeroing above each pivot.
+ You may swap rows if needed. You may scale (mulitply a row by a scalar) as needed. And use scale versions of pivot rows to zero above and below a pivot in the pivot column.

Let's continue with an example.

### An example

Suppose that 
$A \; = \;
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
\end{bmatrix}
$.

The following sequence of row operations will transform $A$ into reduced row echelon form.

1. Notice that the upper left "1" is already a pivot. Replace row 2 with the (current row 2 minus 5 times row 1.)
In symbols, $R_2: R_2 - 5R_1.$  

This elementary row operation will produces

$$ 
A \; = \;
{\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
\end{bmatrix} 
\;
\longrightarrow
\;
\begin{bmatrix}
1 & 2 & 3 & 4 \\
0 & -4 & -8 & -12 \\
9 & 10 & 11 & 12 \\
\end{bmatrix}}
$$

2. Replace row 3 with the (current row 3 minus 9 times row 1.) In symbols, $R_3: R_3 - 9R_1.$

This elementary row operation will produces

$$ 
\begin{bmatrix}
1 & 2 & 3 & 4 \\
0 & -4 & -8 & -12 \\
0 & -8 & -16 & -24 
\end{bmatrix}
$$

3. Now we create a pivot for row 2 by scaling the entire row by $\frac{-1}{4}$ (ie $R_2:\frac{-1}{4}R_2$) to get

$$ 
\begin{bmatrix}
1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 \\
0 & -8 & -16 & -24 
\end{bmatrix}
$$

4. Continuing the process as described, zero out below the 2nd pivot, by replacing current row 3 with row 3 + 8 times row 2. (or $R_3: R_3 + 8R_2$) to get

$$ 
\begin{bmatrix}
1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 \\
0 & 0 & 0 & 0 
\end{bmatrix}
$$

5. We have a bottom row of zeros, this is fine! As a final step we need to zero out above the 2nd pivot. Replace the current row 1 with row 1 minus 2 time row 2 (ie $R_1:R_1 - 2R_2$) to get

$$ 
\begin{bmatrix}
1 & 0 & -1 & -2 \\
0 & 1 & 2 & 3 \\
0 & 0 & 0 & 0 
\end{bmatrix}
$$.

Compare with the`sympy` matrix command `Matrix().rref()` below.

In [3]:
# Always run this cell first! Use shift + enter
import numpy as np
from sympy import Matrix

In [4]:
# An example
A = np.arange(12).reshape(3, 4) + 1
print(A)
print()

# note the difference in how the matrix A is printed from the numpy array vs the Matrix command from SymPy
Matrix(A)


# There is no rref command in numpy. (You should wonder why!)
# There is from the symbolic package SymPy from the Matrix command.
print()
Matrix(A).rref()[0]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]




Matrix([
[1, 0, -1, -2],
[0, 1,  2,  3],
[0, 0,  0,  0]])

## Linear (in)dependence information from the rref of a matrix

Since we were using row combinations to achieve the reduced form of the original matrix $A$, it follows that the reduced matrix is *row equivalent* to $A$. That is to say that the rows of both matrices produce the same set of vectors under row combinations. They contain the same "information".

Further, the pivots gives us valuable information about the independence and dependence of both the rows and the colums of $A$! Any row (or column) of the reduced row echelon form of $A$ containing a pivot is an independent vector relative to the set of rows (or columns!)

We should define what we mean by *dependent* and *independent* vectors. Note that the following definitions are in relation to some set of vectors from a vector space.

Let $a_1, \ldots ,a_m \in \mathbb{R} \;$ and $ \; \textbf{v}_1, \ldots , \textbf{v}_m \in \mathbb{R}^n$. 

The set of vectors is contained in the vector space $\mathbb{R}^n$, and we write $\{\textbf{v}_1, \ldots, \textbf{v}_m \} \subseteq \mathbb{R}^n$.

More generally, if we have scalars $a_1, \ldots, a_m,$ and vectors $\textbf{v}_1, \ldots, \textbf{v}_m \in \mathbb{R}^n $, then

$$a_1 \textbf{v}_1 + \ldots + a_m \textbf{v}_m \in \mathbb{R}^n,$$

and is a linear combination of the vectors, $\textbf{v}_1, \ldots, \textbf{v}_m$ , for any choice of $a_1, \ldots, a_m \in \mathbb{R}.$

Within in the set of vectors if we can write one vector, say $\textbf{v}_1$ as a linear combination of the remaining vectors in the set (not all coefficients equal to zero,) then  $\textbf{v}_1$ is *linearly dependent* and the set is a *linearly independent set* of vectors.

In symbols, if there exists scalars $a_2, \ldots, a_m \in \mathbb{R}$ such that

$$\textbf{v}_1 \; = \; a_2 \textbf{v}_2 + \ldots + a_m \textbf{v}_m$$ 

then $\textbf{v}_1$ is a linearly dependent vector.


## Your turn

We will work on a worksheet together. You will find dependent and linearly dependent vectors by hand using row reduction and check you answers with python code.

In [8]:
# An example
A = [
    [0,1,1,0],
    [-2,1,-1,8],
    [1,-1,-2,-4]
]
print(A)
print()

# note the difference in how the matrix A is printed from the numpy array vs the Matrix command from SymPy
Matrix(A)


# There is no rref command in numpy. (You should wonder why!)
# There is from the symbolic package SymPy from the Matrix command.
# print()
Matrix(A).rref()[0]

[[0, 1, 1, 0], [-2, 1, -1, 8], [1, -1, -2, -4]]



Matrix([
[1, 0, 0, -4],
[0, 1, 0,  0],
[0, 0, 1,  0]])

In [13]:
A = [
    [2, 1, -3, 4],
    [-1, 2, 1, 3],
    [3, -1, 0, -4]
]
Matrix(A).rref()[0]

Matrix([
[1, 0, 0, -3/4],
[0, 1, 0,  7/4],
[0, 0, 1, -5/4]])

In [15]:
A = [
    [3, -1, 0, -6],
    [-2, 0, 6, 2]
]
Matrix(A).rref()[0]

Matrix([
[1, 0, -3, -1],
[0, 1, -9,  3]])

In [17]:
A = [
    [1, 2, 0, -1, -1],
    [2, 4, -3, -2, 1],
    [-1, -2, 6, 1, 5]
]
Matrix(A).rref()[0]

Matrix([
[1, 2, 0, -1, 0],
[0, 0, 1,  0, 0],
[0, 0, 0,  0, 1]])